stages:
  - image
  - lint
  - doc

variables:
  DOCKER_IMAGE_PATH: registry.heptapod.net:443/mercurial/hg-website/ci/default

image: $DOCKER_IMAGE_PATH:stable

# Build an image for the above tasks; this should be a scheduled job, as
# it is quite unnecessary to run on every invocation.
image:build:
  stage: image
  tags:
    - container-registry-push
  needs: []
  # comment these rules for MR modifying the Docker file
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_BUILD_IMAGES == "1"'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  before_script:
    - ""
  script:
    - |
      cat > /kaniko/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "username": "$CI_REGISTRY_USER",
            "password": "$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --single-snapshot
      --cleanup
      --destination $DOCKER_IMAGE_PATH:stable


lint:check:
  stage: lint
  needs:
    - job: "image:build"
      optional: true
  script:
    - pdm sync
    - pdm run format-check


pages:
  stage: doc
  needs:
    - job: "image:build"
      optional: true
  script:
    - pdm sync
    # - pdm run python -m bash_kernel.install
    - pdm build-site
    - mkdir -p public/$CI_COMMIT_REF_NAME
    - rsync -rvc --delete build/html/* public/$CI_COMMIT_REF_NAME/
    # This directory can become too large leading to error.
    # It can be purged with the bottom "Clear runner caches"
    # in https://foss.heptapod.net/mercurial/hg-website/-/pipelines
    - ls public
    - echo "CI_COMMIT_REF_NAME="$CI_COMMIT_REF_NAME
    - echo See https://mercurial.pages.heptapod.net/hg-website/$CI_COMMIT_REF_NAME
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - public
    expire_in: 5 days
  when: always

