version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install pdm
    post_install:
      - pdm use -f $READTHEDOCS_VIRTUALENV_PATH
      - pdm sync

sphinx:
  configuration: source/conf.py
